### ISSUE TITLE
questions for tutor

### ISSUE THREAD

**Issue by klezm** [jmpargana/PRG-Praktikum#1]
- [ ] vectors instead of arrays? 
- [ ] third party libs (boost)
- [ ] can we create a "smart" implementation or do we need to stick to the tasks?
- [ ] are we allowed to create additional classes or functions?
- [ ] which compiler are they using for testing?

no specific answers. we need to ask our own tutor tomorrow

**Comment by jmpargana** [comment]
Hallo Joao,
es ist auch keine Pflicht an den Tutorienterminen teilzunehmen, ihr könnt mir dort Fragen stellen oder einfach per Mail wie jetzt oder einfach zusammen am Projekt arbeiten. Aber ihr müsst auf jeden Fall die Montage nach jeder Abgabe kommen (also 3 mal) und euer Projekt vorstellen bei mir. Solltet ihr mal nicht können, einfach bescheid geben und ihr könnt die Woche drauf vorstellen.

Zu den Fragen:

1. Ja der Typ ist frei. Generell sind die Aufgabenstellungen zwar an ein paar Stellen sehr detailliert, dennoch seid ihr im Allgemeinen beim Programmieren frei. Am Ende sollten auf jeden Fall die generellen Funktionalitäten gehen.

2. Siehe Punkt 1, also ja.

3. Achso ich sehe grade die Fragen beziehen sich eigentlich auf das gleiche. Ja also ihr seid frei, solange das Programm funktioniert und das tut was es tun soll.

4. Ja. Siehe oben.

5. Generell auch offen. Eigentlich sollten verschiedene Compiler auch kein Problem sein, aber Ihr müsst ja bei 3. eh den QT installieren, von daher könnt ihr da auch das Projekt beginnen. 

Liebe Grüße,
Lisa

 

On Tue, Oct 22, 2019 at 10:04 AM Joao Martim Pargana Silva <noreply.olat-request@dlist.server.uni-frankfurt.de> wrote:

    Hallo!

    Ich und die anderen Kommilitonen meiner Gruppe könnten gestern leider nicht zum Tutorium Termin kommen.
    Wir haben paar Fragen für das erste Blatt und generell für das Praktikum.

    1. Es steht auf dem Blatt, dass man Arrays verwenden soll. Ist da die Wahl der Array Type frei? Es gibt in der c++ standard library std::vector, std::list und std::array, aber in der Vorlesung würde nur CType Array beigebracht. Dürfen wir uns da was frei wählen? Oder mindestens std::array statt CType array?

    2. Für späteren Aufgaben, sind auch third party libraries erlaubt?

    3. Müssen wir die Implementierung der Klassen genau wie im Blatt vorgeschlagen ist, oder dürfen wir uns unser eigenes Modell ausdenken, solange das ganze Programm perfekt funktioniert?

    4. Dürfen wir zusätzliche Klassen und Funktionen schreiben, um manche Problemme zu vereinfachen?

    5. Können wir egal welchen Compiler verwenden, oder werden die Aufgaben mit einem bestimmten überprüft.

    Vielen Dank im Voraus!

    Viele Grüße,
